### PR TITLE
Add support for repo/ref inputs

### LINKED ISSUE #7: Feature request: Support overriding repo and ref
I'm finishing up integrating recheck into [apache/arrow](https://github.com/apache/arrow) and have another feature request. This workflow has been super useful so far in testing due to its speed, so thank you for creating it!

For project-specific reasons, we run manually-triggered workflows like this one using a comment bot ([example](https://github.com/apache/arrow/pull/44523#issuecomment-2434122461)). This then runs the matched workflow(s) on using GitHub Actions _on another repository_ ([ursacomputing/crossbow](https://github.com/ursacomputing/crossbow/)) against a checkout of the triggering PR's branch. We also support running the workflows on forks of the crossbow repository so neither repository or ref can be fixed.

As far as I understand it, recheck can't do this at the moment because it checks out the repo and ref that triggered the workflow. I'm not sure if adding support for providing repository and ref would be generally useful but I'll submit a PR so you can have a look. It would at least be useful for us.

### PR DESCRIPTION
**Pull request by amoeba**
Closes #7.

### CODE REVIEW

**Comment by jeroen** [comment]
Thanks!

**Comment by jeroen** [comment]
Hmm I think the documentation repeats too much. I am going to trim it a bit.

**Comment by jeroen** [comment]
Also where was a bug where your example workflow from the readme has a parameter `repo` but the reusable workflow it is called `repository`.

**Comment by amoeba** [comment]
Thanks for the quick merge. Sorry about the mistake in the README!

**Pull request merged**
